#Making native country more readable.
adult$`Native-country` <-gsub('^', 'USA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'USA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other NA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other NA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other NA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Other', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'SA', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Asia', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)
adult$`Native-country` <-gsub('^', 'Europe', adult$`Native-country`)